networks:
  default:
    external:
      name: roboshop

services:
# docker run -d --name mongodb --network=roboshop mongodb:v1
  mongodb:
    image: mongodb

  catalogue:
    image: catalogue
    depends_on: mongodb

  web:
    image: web
    ports:
    - "80:80"
    depends_on: 
    - catalogue
